apiVersion: v1
kind: ConfigMap
metadata:
  name: viewer-config
  namespace: viewer
data:
  TZ: Asia/Tomsk
  HTTP_ADDR: :8080
  REPORTS_DIR: /app/reports
  REPORT_AGENT_ID: "2"
  PLANS_DIR: /app/plans
  XA_CACHE_DIR: /app/xa-cache
  XA_CACHE_TIMEOUT_SECONDS: "120"
  XA_CACHE_FFMPEG_PATH: /usr/bin/ffmpeg
  XA_CACHE_STUDY_WORKERS: "1"
  XA_CACHE_FRAME_WORKERS: "1"
  XA_CACHE_CINE_WORKERS: "1"
  XA_CACHE_CINE_CRF: "23"
  XA_CACHE_BUILD_ARCHIVE: "false"
  XA_CACHE_WARM_EXISTING: "false"
  XA_ARCHIVE_STUDY_WORKERS: "1"
  XA_ARCHIVE_DELETE_PACS: "false"
  XA_ARCHIVE_DELETE_LOCAL: "false"
  STUDY_RETENTION_ENABLED: "false"
  REMOTE_PACS_URL: http://orthanc:8042/instances
  REMOTE_PACS_TIMEOUT_SECONDS: "300"
  REMOTE_PACS_IMPORT_WORKERS: "1"
  YANDEX_BUCKET: agent-dicom
  YANDEX_ENDPOINT: https://storage.yandexcloud.net
  YANDEX_REGION: ru-central1

