apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: viewer
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-data
  namespace: viewer
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reports-data
  namespace: viewer
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plans-data
  namespace: viewer
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xa-cache-data
  namespace: viewer
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi

